### ISSUE TITLE
GiveDBFile.exe가 타 컴퓨터에서 Loading이 안되는 이유(호환성 문제) 해결방법 제시

### ISSUE THREAD

**Issue by vksxk12** [vksxk12/GiveDBFile#1]

**Comment by vksxk12** [comment]
제목 그대로 다른 컴퓨터에서 실행시 오류가 발생합니다
확인해주세요

**Comment by thsghwls** [comment]
exe file 생성시 jsmooth를 사용하였는데 이 프로그램을 통해 나온 실행파일은 학교에서는 실행되지 않았습니다. 문제는 인식하였으나 해결방법은 찾지 못하였고 실행파일 생성하는 다른 오픈소스 프로그램을 사용하였습니다. 이름은 Launch4j이고 이 프로그램을 통해 생성된 실행파일은 실행가능하였습니다. **해결하였으니 이슈를 닫아주세요.**

**Comment by yun-sun-dong** [comment]
컴파일시 정적 라이브러리를 사용하기보다 동적 라이브러리를 사용하면 이런 오류를 조금 줄일 수 있지 않을까요...? 뭘로 컴파일하신지는 모르겠는데... Release 모드로 컴파일을... 해보시는게?
