### ISSUE TITLE
DB와 웹 연동관련 문제

### ISSUE THREAD

**Issue by vksxk12** [vksxk12/GiveDBFile#2]

**Comment by thsghwls** [comment]
무슨문제가 있나요?

**Comment by yun-sun-dong** [comment]
웹 서버 한글 깨짐 -> PHP 웹 인코딩,디코딩시 자동으로 latin으로 인코딩,디코딩 되는 것을 utf-8, euc-kr로 수정  - > db(mysql) 데이터 삽입 시 한글 깨짐 -> table setting을 utf-8으로 설정

**Comment by yun-sun-dong** [comment]
외부 접속이 안됨 -> localhost로만 접속이 가능함 -> 공유기 문제 -> 포트 포워딩을 해야되는데 sk 기가 라이트 H614G 공유기 admin 사이트 접속을 못함... -> 어차피 발표는 원격으로 하기 때문에 원격으로 로컬 사이트 접속 어떻습니까?

**Comment by yun-sun-dong** [comment]
3. 웹 사이트 계정을 생성할 때 비밀번호를 sha1으로 암호화 되어있는데 로그인할 때 비밀번호 입력 시 비밀번호를 받아 다시 sha1으로 암호화하고 db(mysql)과 비교??

**Comment by thsghwls** [comment]
DB는 오라클로통일합시다.
