### ISSUE TITLE
DB와 웹 연동문제 2. 외부 접속 문제

### ISSUE THREAD

**Issue by yun-sun-dong** [vksxk12/GiveDBFile#4]
웹을 열었는데 외부 접속이 안됩니다. (윈도우 7 이상에서는 80포트를 열어주지 않아서 9999포트로 대체)

**Comment by yun-sun-dong** [comment]
외부 접속은 안되고 localhost (127.0.0.1) ip로만 접속이 가능합니다. 제 생각에는 공유기 때문에 포트 포워딩을 해야되는걸로 판단되는데... 공유기 설정 사이트를 접속을 못합니다.(계정 비밀번호를 모름...)

**Comment by yun-sun-dong** [comment]
외부 접속이 안됨 -> localhost로만 접속이 가능함 -> 공유기 문제 -> 포트 포워딩을 해야되는데 sk 기가 라이트 H614G 공유기 admin 사이트 접속을 못함... -> 어차피 발표는 원격으로 하기 때문에 원격으로 로컬 사이트 접속 어떻습니까?

**Comment by thsghwls** [comment]
네 원격으로 합시다.
