### ISSUE TITLE
DB와 웹 연동 문제 3. 로그인 문제

### ISSUE THREAD

**Issue by yun-sun-dong** [vksxk12/GiveDBFile#5]
회원가입을 할때 비밀번호를 sha1으로 암호화하여 DB에 저장하는데...
Web에서 로그인 정보를 비교할 때 입력받은 비밀번호를 다시 sha1으로 암호화하여 비교하여야 하는지..?

**Comment by thsghwls** [comment]
그게맞을꺼같네요

**Comment by vksxk12** [comment]
다른 편한 방법 있으면 그쪽으로 해도 됩니다
