### ISSUE TITLE
테이블 명 보는것처럼 DB에서 View이름만 출력하는 sql문이 뭐가있을까요?

### ISSUE THREAD

**Issue by thsghwls** [vksxk12/GiveDBFile#6]
실제로는 View를 출력한다는 개념에서 프로젝트를 진행하고 있는데 지금은 table명을 추출하여 선택할 수 있도록 만들어져있습니다. view이름을 출력하는 질의가 뭐가있을까요?

**Comment by vksxk12** [comment]
DB에서 추출한 데이터를 엑셀 파일로 저장하는데 View를 거칠 필요없이 바로 table을 참조하여 하는 것이
더 편하지 않습니까?
그리고 'view이름을 출력하는 질의가 뭐가있을까요?' 에 대한 질문은 잘 모르겠습니다

**Comment by thsghwls** [comment]
테이블을 참조할때는 select table_name from tabs;를 사용했구요 컬럼은 desc 선택된테이블이름;을 사용하였습니다. Select * from views;도 되는지 확인해봐야겠네요

**Comment by thsghwls** [comment]
어짜피 발표시 테이블이 조회되는걸 보여야하니까 view를 생성해서 보이는것보단 Table을 여러개 조회가능하다는걸 보이는게 낫겠네요. Close하겠습니다.
