### ISSUE TITLE
ppt 관련문제

### ISSUE THREAD

**Issue by vksxk12** [vksxk12/GiveDBFile#7]
ppt 내용에 관하여 만든 이슈입니다

**Comment by thsghwls** [comment]
1.제목  2.목표 3.사용한 오픈소스 툴과 api (그림으로  보이고 간략하게 뭐하기위해 썼는지 설명하구) 4.git사용 5.결과(어떤걸 구현했는지)  6.시연  하면될것같네요

**Comment by vksxk12** [comment]
현제 작업내역
1. 제목   2. 프로젝트 목표    3. 사용 오픈소스/툴      4. 데모 사용법    5. 이슈     6.위키       7. 시연 or 동영상 
순입니다

**Comment by vksxk12** [comment]
3번 같은 경우 그림은 ppt로 보여주나 따로 대본이 있어야 할듯 합니다

**Comment by thsghwls** [comment]
제 생각은 apache poi의 경우 아파치 포이 홈페이지 스크린샷해서 붙이고 간략하고 큰글씨로 java에서 excel사용할수있도록 지원하는 api라고하면될꺼같아요

**Comment by thsghwls** [comment]
데모사용법은뭐죠?

**Comment by vksxk12** [comment]
학교에서와 같이 바로 사용이 불가능하니 그에 대한 사전 준비입니다

**Comment by thsghwls** [comment]
데모사용법은 시연전에 하는게 좋을거같아요

**Comment by vksxk12** [comment]
그러면 시연을 5.6번 앞으로 하는것이 좋습니까?
사용법, 시연, 이슈,위키순

**Comment by thsghwls** [comment]
네 그게좋겠네요

**Comment by vksxk12** [comment]
wiki 사전준비에 대한 내용 추가해주세요 
정확히 잘 모르겠습니다

**Comment by thsghwls** [comment]
위키에는 이름 목적과 사용 툴 과 api 그리고 사용방법 :
오라클 jdbc드라이버를 java jre lib ext(인가?) 에다가 저장하고 java 프로그램이기때문에 java가 깔려있고 환경변수는 설정되어있어야한다는 설명 넣으면될꺼에요

**Comment by thsghwls** [comment]
툴은 lms에 보셨을꺼에요. 개발언어에 php는 빠졌는데 그것만따로추가하시면되요

**Comment by vksxk12** [comment]
정확히 무엇을 말씀하시는지 모르겠습니다.
틀린것 혹은 필요한 것이 있으면 Wiki -> Edit 누르셔서 수정해주세요

**Comment by thsghwls** [comment]
추가완료했습니다.
