### ISSUE TITLE
GIT에 실행파일도 쓸수있도록 올려야하는데 어떻게 올리죠?

### ISSUE THREAD

**Issue by thsghwls** [vksxk12/GiveDBFile#8]
아시는분?

**Comment by vksxk12** [comment]
Upload files를 이용하시면 됩니다.
파일을 올렸으니 확인해주세요

**Comment by vksxk12** [comment]
올릴때 lms에 있는 압축파일채로 올렸으니 수정하실것 있으시면 수정하시면 됩니다
파일명 GiveDBFile%28Final_Icon%29.zip

**Comment by thsghwls** [comment]
네 알겠습니다.
